### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by tonyguadagno** [evuraan/MythicalMythTV#1]
hi, thanks so much for doing this, i have wanted a roku frontend for a long time.  i have a question about maestro...does maestro convert all recordings "just in case" or does it convert the recordings "on demand"?  is there any issue with running maestro on the myth backend?

thanks again

**Comment by evuraan** [comment]
Hi @tonyguadagno 

> does maestro convert all recordings "just in case" or does it convert the recordings "on demand"?


`maestro` does not convert the recordings at all - it merely picks up Videos from your `recordingsPath` folder. you would need to process your recordings to suit your needs. Please see [video-processing.](https://github.com/evuraan/MythicalMythTV/tree/main/maestro#video-processing)

> is there any issue with running maestro on the myth backend?

See [usage](https://github.com/evuraan/MythicalMythTV/tree/main/maestro#usage). 

As long as it can access your `recordingsPath` folder and `mythBE`, `dbHost`  endpoints, you can run from anywhere. Mine lives on the mythbackend server since everything maestro needs is local there. 

Hope this helps!

**Comment by evuraan** [comment]
"On the fly" encoding is now available. 

Please see: 
https://github.com/evuraan/MythicalMythTV/tree/main/maestro#on-the-fly-encoding
