### ISSUE TITLE
roku app exits after splash screen

### ISSUE THREAD

**Issue by tonyguadagno** [evuraan/MythicalMythTV#11]
hi, i noticed you had a new version so i decided to upgrade and try it again.  i am noticing that after i configure the maestro url, the splash screen comes up and then it just boots me back to the main roku menu..

any ideas?

**Comment by evuraan** [comment]
- What happens when you relaunch?
- Can roku resolve/connect your maestro url?
- From a browser in the same network as your roku, are you able to go to your `maestro_url/hello?123` ? What does it say?
- If you run `maestro` with `-debug` flag, does it show anything when your roku app is starting up?  Something like below should be logged:

```bash
...
Listening on:
  1  http://127.0.0.1:8081/
  2  http://192.168.1.5:8081/

Feed request from 192.168.1.4:44724
..
```

**Comment by tonyguadagno** [comment]
ok, that was the issue, i fat fingered the url.  this makes me think it would be great if you could allow the app to start even if the url was wrong and allow the user to change it.

as it stands, i have to remove the app, reinstall it and then re-configure it.
thanks
